using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Content.Client._Impstation.DebrisAccumulator.UI;

[GenerateTypedNameReferences]
public sealed partial class DebrisAccumulatorWreckInfoDisplay : BoxContainer
{


    public DebrisAccumulatorWreckInfoDisplay()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

}
