namespace Content.Server._Impstation.GalacticMarket;

/// <summary>
/// This is used for...
/// </summary>
[RegisterComponent]
public sealed partial class GalacticMarketComponent : Component
{
    /// <summary>
    /// how many spesos have been generated by selling a given thing
    /// </summary>
    /// <returns></returns>
    [DataField]
    public Dictionary<string, double> SpesosGenerated = [];
}
